#!/usr/bin/env bash
# Publishes the rendered report: SVG cards to the assets branch, the comment on the
# PR (one per marker, edited on every push) and the job summary.
#
# Never fails the job: every step that needs write access degrades to a warning
# (Dependabot and fork PRs get a read-only token) and the job summary is always written.
set -uo pipefail

: "${OUT:?}" "${REPO:?}" "${MARKER:?}" "${COMMENT:?}" "${CARDS:?}" "${ASSETS_BRANCH:?}"
PR="${PR:-}"
SHA7="${HEAD_SHA:0:7}"

comment="$OUT/comment-plain.md"

# --- 1. cards ------------------------------------------------------------------------
upload_cards() {
  local branch="$ASSETS_BRANCH" dir="pr-${PR}/${SHA7}"

  if ! gh api "repos/$REPO/branches/$branch" --silent 2>/dev/null; then
    # Orphan branch: no history shared with the code, holds only generated images.
    local blob tree commit
    blob=$(gh api "repos/$REPO/git/blobs" -f encoding=utf-8 \
      -f content=$'# coverage-assets\n\nSVG cards generated by the coverage report of each PR (Dogfy-Diet/.github/actions/coverage-report). Do not edit.\n' --jq .sha) || return 1
    tree=$(gh api "repos/$REPO/git/trees" --input - --jq .sha <<<"{\"tree\":[{\"path\":\"README.md\",\"mode\":\"100644\",\"type\":\"blob\",\"sha\":\"$blob\"}]}") || return 1
    commit=$(gh api "repos/$REPO/git/commits" -f message="chore: init coverage-assets" -f tree="$tree" --jq .sha) || return 1
    gh api "repos/$REPO/git/refs" -f ref="refs/heads/$branch" -f sha="$commit" --silent || return 1
  fi

  local f current
  for f in hero-light hero-dark files-light files-dark; do
    # A re-run of the same commit overwrites its cards: the contents API needs the current blob sha.
    current=$(gh api "repos/$REPO/contents/$dir/$f.svg?ref=$branch" --jq .sha 2>/dev/null || true)
    gh api -X PUT "repos/$REPO/contents/$dir/$f.svg" \
      -f message="chore: coverage cards for #$PR ($SHA7)" -f branch="$branch" \
      -f content="$(base64 -w0 <"$OUT/$f.svg")" ${current:+-f sha="$current"} --silent || return 1
  done
}

if [ "$CARDS" = "true" ] && [ -n "$PR" ]; then
  if upload_cards; then
    comment="$OUT/comment-cards.md"
  else
    echo "::warning title=coverage-report::No se pudieron subir las tarjetas SVG a '$ASSETS_BRANCH' (¿token sin contents: write?). Se publica la versión sin imágenes."
  fi
fi

# --- 2. job summary --------------------------------------------------------------------
if [ -n "${GITHUB_STEP_SUMMARY:-}" ]; then
  cat "$comment" >>"$GITHUB_STEP_SUMMARY"
fi

# --- 3. PR comment -----------------------------------------------------------------------
if [ "$COMMENT" != "true" ] || [ -z "$PR" ]; then
  exit 0
fi

existing=$(gh api --paginate "repos/$REPO/issues/$PR/comments" \
  --jq ".[] | select(.body | startswith(\"<!-- $MARKER -->\")) | .id" 2>/dev/null | head -n1)

if [ -n "$existing" ]; then
  gh api -X PATCH "repos/$REPO/issues/comments/$existing" -F body=@"$comment" --silent \
    || echo "::warning title=coverage-report::No se pudo actualizar el comentario de coverage (¿token sin pull-requests: write?)."
else
  gh api "repos/$REPO/issues/$PR/comments" -F body=@"$comment" --silent \
    || echo "::warning title=coverage-report::No se pudo publicar el comentario de coverage (¿token sin pull-requests: write?)."
fi
exit 0
